### ISSUE TITLE
Start app without declared routes causes error

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/gomek#57]
The following setup has no declared routes:

```

func main() {
	c := gomek.Config{}
	app := gomek.New(c)

	app.Use(gomek.Logging)
	app.Use(gomek.CORS)

	app.Listen(3000)
	err := app.Start()
	if err != nil {
		panic(err)
	}
}

```

Causes the following error:

```


```GOROOT=/Users/<user>/go/go1.21.4 #gosetup
GOPATH=/Users/<user>/go #gosetup
/Users/<user>/go/go1.21.4/bin/go build -o /private/var/folders/tx/gp9spzw93kxbrx3syxq3lgd00000gp/T/GoLand/___messaging_api github.com/<user>/messager-app/messaging_api #gosetup
/private/var/folders/tx/gp9spzw93kxbrx3syxq3lgd00000gp/T/GoLand/___messaging_api
panic: http: invalid pattern

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x14000022280, {0x0, 0x0}, {0x1007fa1b8?, 0x1400000e180})
        /Users/<user>/go/go1.21.4/src/net/http/server.go:2524 +0x220
net/http.(*ServeMux).HandleFunc(...)
        /Users/<user>/go/go1.21.4/src/net/http/server.go:2567
github.com/<user>/gomek.(*View).Create(0x30?, 0x14000148028, 0x14000148178, 0x14000133ce8?, {{0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...})
        /Users/<user>/go/pkg/mod/github.com/<user>/gomek@v0.4.7/view.go:62 +0x478
github.com/<user>/gomek.(*App).setup(0x14000148000)
        /Users/<user>/go/pkg/mod/github.com/<user>/gomek@v0.4.7/gomek.go:132 +0x2b0
github.com/<user>/gomek.(*App).Start(0x14000148000)
        /Users/<user>/go/pkg/mod/github.com/<user>/gomek@v0.4.7/gomek.go:372 +0x24
main.main()
        /Users/<user>/GolandProjects/messager-app/messaging_api/main.go:13 +0x214

**Comment by rafiramadhana** [comment]
@joegasewicz may i know the expectation here?

are we going to throw a defined error when route is not set?

or maybe we will handle the case when the route is not set to avoid panic?

thanks

**Comment by rafiramadhana** [comment]
could this relate with https://github.com/joegasewicz/gomek/issues/35?

**Comment by joegasewicz** [comment]
@rafiramadhana

> or maybe we will handle the case when the route is not set to avoid panic?

 This sounds like the best solution & I think we should just log a warning the std out, no panics. Thanks
